#!/bin/bash

TERM=xterm-256color

run() {
  exec=$1
  printf "\x1b[38;5;104m --> ${exec}\x1b[39m\n"
  eval ${exec}
}

say () {
  say=$1
  printf "\x1b[38;5;220m${say}\x1b[38;5;255m\n"
}

# Extract existing values from current hotspot script
OLDFREQ=$(grep -m1 'sa818 .* radio' /usr/sbin/hotspot | sed -n 's/.*--frequency \([^ ]*\).*/\1/p')
CPVOL=$(grep -m1 'sa818 .* volume' /usr/sbin/hotspot | sed -n 's/.*--level \([^ ]*\).*/\1/p')

# Extract full --ctcss parameter (exactly as written)
CTCSS=$(grep -m1 'sa818 .* radio' /usr/sbin/hotspot | sed -n 's/.*\(--ctcss [^ ]*\).*/\1/p')

gum style --border normal --margin "1" --padding "1 2" \
  --border-foreground "#04B575" \
  "$(gum style --foreground 3 'RF.')Guru $(gum style --foreground 3 '-') Hotspot Frequency"

gum style --foreground "#04B575" "Frequency:"
FREQ=$(gum input --value "${OLDFREQ}")

gum style --foreground 212 "${FREQ}"

rm /usr/sbin/hotspot
say "Configuring hotspot"

{
  echo "#!/bin/bash"
  echo ""
  echo "sa818 --port /dev/ttyAMA0 radio --bw 0 --frequency ${FREQ} ${CTCSS} --squelch 8"
  echo "sa818 --port /dev/ttyAMA0 filters --emphasis disable --highpass disable --lowpass disable"
  echo "sa818 --port /dev/ttyAMA0 volume --level ${CPVOL}"
} > /usr/sbin/hotspot

chmod +x /usr/sbin/hotspot
run "/usr/sbin/hotspot"
