#!/bin/bash

sa818 --port /dev/ttyAMA0 radio --bw 0 --frequency 434.925 --ctcss 250.3,0 --tail close --squelch 8
sa818 --port /dev/ttyAMA0 filters --emphasis disable --highpass disable --lowpass disable
sa818 --port /dev/ttyAMA0 volume --level 1
