#!/bin/bash

TERM=xterm-256color

run() {
  exec=$1
  printf "\x1b[38;5;104m --> ${exec}\x1b[39m\n"
  eval ${exec}
}

say () {
  say=$1
  printf "\x1b[38;5;220m${say}\x1b[38;5;255m\n"
}

OLDFREQ=$(grep freq /usr/sbin/hotspot | awk '{ print $7}')
CPVOL=$(grep volume /usr/sbin/hotspot | awk '{ print $6}'| tail -n 1)

gum style --border normal --margin "1" --padding "1 2" --border-foreground "#04B575" "$(gum style --foreground 3 'RF.')Guru $(gum style --foreground 3 '-') Hotspot Frequency"

gum style --foreground "#04B575" "Frequency:"
FREQ=$(gum input --value "${OLDFREQ}")

gum style --foreground 212 "${FREQ}"

rm /usr/sbin/hotspot
say "Configuring hotspot"
echo "#!/bin/bash" > /usr/sbin/hotspot
echo "" >> /usr/sbin/hotspot
echo "sa818 --port /dev/ttyAMA0 radio --bw 1 --frequency ${FREQ} --squelch 8" >> /usr/sbin/hotspot
echo "sa818 --port /dev/ttyAMA0 filters --emphasis disable --highpass disable --lowpass disable" >> /usr/sbin/hotspot
echo "sa818 --port /dev/ttyAMA0 volume --level ${CPVOL}" >> /usr/sbin/hotspot
chmod +x /usr/sbin/hotspot
run "/usr/sbin/hotspot"
