#!/bin/bash

run() {
  exec=$1
  printf "\x1b[38;5;104m --> ${exec}\x1b[39m\n"
  eval ${exec}
}

say () {
  say=$1
  printf "\x1b[38;5;220m${say}\x1b[38;5;255m\n"
}


say "Installing Prerequisites"
run "apt -y update"
run "apt -y upgrade"
run "apt -y install libqmi-utils udhcpc"


say "Installing 4G"
run "cd /tmp"
run "wget -O /etc/hotspot-4g.conf https://raw.githubusercontent.com/Guru-RF/Analog-HotSPOT-SVXLink/master/hotspot-4g.conf"
run "wget -O /usr/sbin/hotspot-4g https://raw.githubusercontent.com/Guru-RF/Analog-HotSPOT-SVXLink/master/hotspot-4g"
run "chmod +x /usr/sbin/hotspot-4g"
run "wget -O /usr/sbin/hotspot-4g-config https://raw.githubusercontent.com/Guru-RF/Analog-HotSPOT-SVXLink/master/hotspot-4g-config"
run "chmod +x /usr/sbin/hotspot-4g-config"
run "wget -O /etc/systemd/system/hotspot-4g.service https://raw.githubusercontent.com/Guru-RF/Analog-HotSPOT-SVXLink/master/hotspot-4g.service"
run "wget -O /etc/systemd/system/disable-wlan.service https://raw.githubusercontent.com/Guru-RF/Analog-HotSPOT-SVXLink/master/disable-wlan.service"
run "wget -O /etc/systemd/system/disable-wlan.timer https://raw.githubusercontent.com/Guru-RF/Analog-HotSPOT-SVXLink/master/disable-wlan.timer"
run "systemctl daemon-reload"

say "Disabling ModemManager (conflicts with qmicli on /dev/cdc-wdm0)"
run "systemctl disable --now ModemManager.service 2>/dev/null || true"
run "systemctl mask ModemManager.service 2>/dev/null || true"

say "Starting 4G"
run "systemctl enable disable-wlan.timer"
run "systemctl enable hotspot-4g.service"

say "Reboot the system (sudo reboot)"
