#!/bin/bash

if [ "$EUID" -ne 0 ]; then
	printf "\x1b[38;5;196mThis script must be run as root. Exiting...\x1b[39m\n"
	exit 1
fi
run() {
	exec=$1
	printf "\x1b[38;5;104m --> ${exec}\x1b[39m\n"
	eval ${exec}
}

say() {
	say=$1
	printf "\x1b[38;5;220m${say}\x1b[38;5;255m\n"
}

if [ "$EUID" -ne 0 ]; then
	say "Please run as root"
	exit
fi

say "Stop svxlink"
run "systemctl stop svxlink"
say "remove old kernels"
bash ./remove-old-kernels.sh
say "cleanup logs"
bash ./cleanup-pi.sh
say "install default configs"
cat svxlink.conf.hsdefault >/etc/svxlink/svxlink.conf
cat node_info.json.hsdefault >/etc/svxlink/node_info.json
say "remove ssh keys"
/bin/rm -v /etc/ssh/ssh_host_*
say "remove pki's"
/bin/rm -v /var/lib/svxlink/pki/*
say "install default hotspot config and frequency"
cat hotspot-uhf >/usr/sbin/hotspot

say "Install auto-expand-rootfs"
run "cp auto-expand-rootfs /usr/sbin/auto-expand-rootfs"
run "chmod +x /usr/sbin/auto-expand-rootfs"
run "touch /expand-rootfs"

say "Install auto-expand-rootfs.service"
run "cp auto-expand-rootfs.service /lib/systemd/system/auto-expand-rootfs.service"
run "systemctl enable auto-expand-rootfs.service"

say "Install ssh-gen-keys.service"
run "cp ssh-gen-keys.service /lib/systemd/system/ssh-gen-keys.service"
run "systemctl enable ssh-gen-keys"
run "systemctl daemon-reload"

say "remove svxspot repo and ha"
cd ..
rm -fr Analog-HotSPOT-SVXLink
touch /needsconfig
say "run as hotspot user:"
say "> history -c && history -w"
say "run as root user: (sudo su -)"
say "> history -c && history -w && nmcli connection delete preconfigured && halt"
